<template>
  <v-card>
    <v-tabs
      bg-color="deep-purple-darken-4"
      center-active
    >
      <v-tab>Enero</v-tab>
      <v-tab>Febrero</v-tab>
      <v-tab>Marzo</v-tab>
      <v-tab>Abril</v-tab>
      <v-tab>Mayo</v-tab>
      <v-tab>Junio</v-tab>
      <v-tab>Julio</v-tab>
      <v-tab>Agosto</v-tab>
      <v-tab>Septiembre</v-tab>
      <v-tab>Octubre</v-tab>
      <v-tab>Noviembre</v-tab>
      <v-tab>Diciembre</v-tab>
    </v-tabs>
  </v-card>
</template>
